CREATE TABLE Persona (
  ID_Persona INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CI VARCHAR(8) NOT NULL UNIQUE,
  Email VARCHAR(100) NOT NULL,
  Contraseña VARCHAR(100) NOT NULL,
  Rol ENUM('Usuario','Interesado','Admin'),
  Nombre VARCHAR(100) NOT NULL,
  Apellido VARCHAR(100) NOT NULL
);

CREATE TABLE Admin (
  ID_Persona INT NOT NULL PRIMARY KEY,
  Nivel_permisos ENUM('Operador','Admin'),
  Foto VARCHAR(100),
  Fecha_ingreso DATE,
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona)
);

CREATE TABLE Usuario (
  ID_Persona INT NOT NULL PRIMARY KEY,
  Fecha_nacimiento DATE,
  Fecha_ingreso DATE,
  Foto VARCHAR(100),
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona)
);

CREATE TABLE Interesado (
  ID_Persona INT NOT NULL PRIMARY KEY,
  Antecedentes VARCHAR(255),
  Estado_entrevista ENUM('En espera','Pendiente','Aprobado','Rechazado'),
  Estado_antecedentes ENUM('En espera','Pendiente','Aprobado','Rechazado'),
  Fecha_entrevista DATE,
  Hora_entrevista TIME,
  Pago_inicial VARCHAR(255),
  Estado_pago_inicial ENUM('En espera','Pendiente','Aprobado','Rechazado'),
  Monto_pago_inicial INT,
  Unidad_Habitacional_Asignada TINYINT(1) DEFAULT 0,
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona)
);

CREATE TABLE Numero_de_telefono (
  ID_Telefono INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_Persona INT,
  Telefono INT,
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona)
);

CREATE TABLE Integrante_Familiar (
  ID_Integrante INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_Persona INT NOT NULL,
  Nombre VARCHAR(100) NOT NULL,
  Apellido VARCHAR(100) NOT NULL,
  CI VARCHAR(20) NOT NULL UNIQUE,
  FechaNacimiento DATE,
  Email VARCHAR(150),
  Genero ENUM('Masculino','Femenino') NOT NULL,
  Parentesco VARCHAR(50),
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Semana_trabajo (
  ID_Semana_trabajo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Horas_semanales INT DEFAULT 21,
  Fecha_semana DATE NOT NULL UNIQUE
);

CREATE TABLE Horas_Trabajadas (
  ID_Horas_trabajadas INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Horas INT,
  Fecha_registro_horas DATE,
  ID_Persona INT,
  ID_Semana_trabajo INT NOT NULL,
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona),
  FOREIGN KEY (ID_Semana_trabajo) REFERENCES Semana_trabajo(ID_Semana_trabajo)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Falta (
  ID_Comprobante_pago INT,
  ID_Falta INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_Persona INT NOT NULL,
  ID_Semana_trabajo INT NOT NULL,
  Motivo_falta VARCHAR(255) NOT NULL,
  Horas_solicitadas INT NOT NULL,
  Estado ENUM('En espera','Aprobada','Rechazada'),
  Fecha DATE,
  Tipo_falta ENUM('Exoneracion', 'Pago Compensatorio') NOT NULL,
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona),
  FOREIGN KEY (ID_Semana_trabajo) REFERENCES Semana_trabajo(ID_Semana_trabajo)
);

CREATE TABLE Comprobante_pago (
  ID_Comprobante_pago INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_Persona INT,
  Motivo_pago VARCHAR(255),
  Estado_pago ENUM('En espera','Pendiente','Aprobado','Rechazado'),
  Mes DATE,
  Foto VARCHAR(255),
  Monto INT,
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona)
);

CREATE TABLE Unidad_habitacional (
  ID_Unidad_habitacional INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_Persona INT,
  Numero_puerta VARCHAR(20),
  Pasillo VARCHAR(20),
  Estado_unidad ENUM('En espera','En pausa','En construcción','Finalizada'),
  Cantidad_habitaciones INT,
  FOREIGN KEY (ID_Persona) REFERENCES Persona(ID_Persona)
);

CREATE TABLE Traducciones (
  pagina VARCHAR(100) NOT NULL,
  clave VARCHAR(100) NOT NULL,
  idioma VARCHAR(10) NOT NULL,
  texto TEXT NOT NULL,
  PRIMARY KEY (pagina, clave, idioma)
);

CREATE TABLE tokens (
  Token VARCHAR(512) NOT NULL,
  ID_Persona INT NOT NULL PRIMARY KEY,
  Fecha_creacion DATE NOT NULL,
  Fecha_expiracion DATE NOT NULL
);

CREATE TABLE reunion (
    ID_Reunion INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion VARCHAR(255),
    Fecha DATE NOT NULL,
    Hora TIME NOT NULL,
    Lugar VARCHAR(150),
    Tipo_Reunion ENUM('General','Comisión','Emergencia','Planificacion') NOT NULL,
    Estado_Reunion ENUM('Pendiente','En curso','Finalizada','Cancelada') NOT NULL DEFAULT 'Pendiente'
);

CREATE TABLE asistencia (
    ID_Asistencia INT AUTO_INCREMENT PRIMARY KEY,
    ID_Reunion INT NOT NULL,
    ID_Persona INT NOT NULL,
    Asistencia BOOLEAN NOT NULL DEFAULT FALSE,
    
    FOREIGN KEY (ID_Reunion) REFERENCES reunion(ID_Reunion),
    FOREIGN KEY (ID_Persona) REFERENCES persona(ID_Persona)
);

-- CAMBIAR TRADUCCIONES A EL FORMATO ACTUAL
INSERT INTO `Traducciones` (`pagina`, `clave`, `idioma`, `texto`) VALUES
('landing','header-nav','en','Home;Values;Services;FAQ;Contact'),
('landing','iniciarsesion-btn','en','Log in'),
('landing','hero-titulo','en','Driving collective growth'),
('landing','hero-texto','en','Senda Firme is a cooperative committed to the economic and social development of its members through responsible financial services and personalized advice.'),
('landing','hero-btn','en','Our services'),
('landing','que-hacemos-btn','en','Apply for membership'),
('landing','hero-stat1-label','en','Members'),
('landing','hero-stat2-label','en','In savings'),
('landing','hero-stat3-label','en','Satisfaction'),
('landing','valores-titulo','en','Our cooperative values'),
('landing','valores-subtitulo','en','Principles that guide us and strengthen us as a community'),
('landing','valores-card1-titulo','en','Mutual support'),
('landing','valores-card1-texto','en','We work together to achieve common goals and improve the quality of life of our members.'),
('landing','valores-card2-titulo','en','Security'),
('landing','valores-card2-texto','en','We protect the resources of our members with high standards of safety and transparency.'),
('landing','valores-card3-titulo','en','Community development'),
('landing','valores-card3-texto','en','We drive the economic growth of our community through responsible investments.'),
('landing','servicios-titulo','en','Our financial services'),
('landing','servicios-subtitulo','en','Solutions designed for the needs of our community'),
('landing','servicios-card1-titulo','en','Programmed savings'),
('landing','servicios-card1-texto','en','Plan your future with our flexible savings plans and reach your financial goals.'),
('landing','servicios-card2-titulo','en','Solidarity loans'),
('landing','servicios-card2-texto','en','Access loans with preferential rates for productive and personal projects.'),
('landing','servicios-card3-titulo','en','Financial advisory'),
('landing','servicios-card3-texto','en','Receive personalized guidance to optimize your resources and make better decisions.'),
('landing','servicios-link','en','Learn more'),
('landing','faq-titulo','en','Frequently asked questions'),
('landing','faq-subtitulo','en','We answer your questions about our cooperative'),
('landing','faqs-titulo1','en','What happens when I register?'),
('landing','faqs-texto1','en','Once your registration is complete, our team will contact you to schedule an interview and explain the next steps.'),
('landing','faqs-titulo2','en','What do I need to qualify?'),
('landing','faqs-texto2','en','We require commitment to cooperative values, active participation in assemblies, and contribution to the common project.'),
('landing','faqs-titulo3','en','How much do I have to work in the cooperative?'),
('landing','faqs-texto3','en','Work varies depending on the project, but all members contribute at least 21 hours per week to community activities.'),
('landing','faqs-titulo4','en','Do you have any more questions?'),
('landing','faqs-texto4','en','Contact us via WhatsApp and we will get back to you shortly.'),
('landing','comunidad-titulo','en','Ready to join our community?'),
('landing','comunidad-texto','en','Become part of a cooperative that grows together. Enjoy exclusive benefits and contribute to the economic development of your community.'),
('landing','cta-btn-whatsapp','en','Contact via WhatsApp'),
('landing','footer-descripcion','en','A financial cooperative committed to the economic and social development of our community.'),
('landing','footer-enlaces-titulo','en','Quick links'),
('landing','footer-servicios-titulo','en','Services'),
('landing','footer-contacto-titulo','en','Contact'),
('landing','footer-enlaces','en','Home;Values;Services;FAQ;Contact'),
('landing','footer-servicios','en','Programmed savings;Solidarity loans;Financial advisory;Investments;Insurance'),
('landing','footer-contacto-direccion','en','Maipú 1764, Montevideo'),
('landing','footer-contacto-telefono','en','Phone: +598 92 204 459'),
('landing','footer-contacto-email','en','Email: quartecgaze@gmail.com'),
('landing','footer-contacto-whatsapp','en','Send us a WhatsApp'),
('landing','footer-derechos','en','© 2025 Senda Firme. All rights reserved.'),
('landing','header-nav','es','Inicio;Valores;Servicios;Preguntas;Contacto'),
('landing','iniciarsesion-btn','es','Iniciar sesión'),
('landing','hero-titulo','es','Impulsando el crecimiento colectivo'),
('landing','hero-texto','es','Senda Firme es una cooperativa comprometida con el desarrollo económico y social de sus miembros a través de servicios financieros responsables y asesoramiento personalizado.'),
('landing','hero-btn','es','Nuestros servicios'),
('landing','que-hacemos-btn','es','Tramitar ingreso'),
('landing','hero-stat1-label','es','Miembros'),
('landing','hero-stat2-label','es','En ahorros'),
('landing','hero-stat3-label','es','Satisfacción'),
('landing','valores-titulo','es','Nuestros valores cooperativos'),
('landing','valores-subtitulo','es','Principios que nos guían y nos fortalecen como comunidad'),
('landing','valores-card1-titulo','es','Ayuda mutua'),
('landing','valores-card1-texto','es','Trabajamos juntos para alcanzar objetivos comunes y mejorar la calidad de vida de nuestros miembros.'),
('landing','valores-card2-titulo','es','Seguridad'),
('landing','valores-card2-texto','es','Protegemos los recursos de nuestros asociados con altos estándares de seguridad y transparencia.'),
('landing','valores-card3-titulo','es','Desarrollo comunitario'),
('landing','valores-card3-texto','es','Impulsamos el crecimiento económico de nuestra comunidad mediante inversiones responsables.'),
('landing','servicios-titulo','es','Nuestros servicios financieros'),
('landing','servicios-subtitulo','es','Soluciones diseñadas para las necesidades de nuestra comunidad'),
('landing','servicios-card1-titulo','es','Ahorro programado'),
('landing','servicios-card1-texto','es','Planificá tu futuro con nuestros planes de ahorro flexibles y alcanzá tus metas financieras.'),
('landing','servicios-card2-titulo','es','Créditos solidarios'),
('landing','servicios-card2-texto','es','Accedé a créditos con tasas preferenciales para proyectos productivos y personales.'),
('landing','servicios-card3-titulo','es','Asesoría financiera'),
('landing','servicios-card3-texto','es','Recibí orientación personalizada para optimizar tus recursos y tomar mejores decisiones.'),
('landing','servicios-link','es','Conocer más'),
('landing','faq-titulo','es','Preguntas frecuentes'),
('landing','faq-subtitulo','es','Respondemos tus dudas sobre nuestra cooperativa'),
('landing','faqs-titulo1','es','¿Qué pasa al momento de registrarme?'),
('landing','faqs-texto1','es','Una vez completado tu registro, nuestro equipo se pondrá en contacto para programar una entrevista y explicarte los próximos pasos.'),
('landing','faqs-titulo2','es','¿Qué necesito para ser apto?'),
('landing','faqs-texto2','es','Requerimos compromiso con los valores cooperativos, participación activa en las asambleas y contribución al proyecto común.'),
('landing','faqs-titulo3','es','¿Qué tanto hay que trabajar en la cooperativa?'),
('landing','faqs-texto3','es','El trabajo varía según el proyecto, pero todos los miembros contribuyen con al menos 21 horas semanales a las actividades comunitarias.'),
('landing','faqs-titulo4','es','¿Tenés más preguntas?'),
('landing','faqs-texto4','es','Contactanos por WhatsApp y te responderemos a la brevedad.'),
('landing','comunidad-titulo','es','¿Listo para unirte a nuestra comunidad?'),
('landing','comunidad-texto','es','Formá parte de una cooperativa que crece junta. Disfrutá de beneficios exclusivos y contribuí al desarrollo económico de tu comunidad.'),
('landing','cta-btn-whatsapp','es','Contactar por WhatsApp'),
('landing','footer-descripcion','es','Una cooperativa financiera comprometida con el desarrollo económico y social de nuestra comunidad.'),
('landing','footer-enlaces-titulo','es','Enlaces rápidos'),
('landing','footer-servicios-titulo','es','Servicios'),
('landing','footer-contacto-titulo','es','Contacto'),
('landing','footer-enlaces','es','Inicio;Valores;Servicios;Preguntas;Contacto'),
('landing','footer-servicios','es','Ahorro programado;Créditos solidarios;Asesoría financiera;Inversiones;Seguros'),
('landing','footer-contacto-direccion','es','Maipú 1764, Montevideo'),
('landing','footer-contacto-telefono','es','Teléfono: +598 92 204 459'),
('landing','footer-contacto-email','es','Correo: quartecgaze@gmail.com'),
('landing','footer-contacto-whatsapp','es','Envíanos un WhatsApp'),
('landing','footer-derechos','es','© 2025 Senda Firme. Todos los derechos reservados.'),
('login', 'footer', 'en', '© 2025 Senda Firme. All rights reserved.'),
('login', 'footer', 'es', '© 2025 Senda Firme. Todos los derechos reservados.'),
('login', 'form-login', 'en', 'National ID card;Password'),
('login', 'form-login', 'es', 'Cedula de Identidad;Contraseña'),
('login', 'login-beneficio1', 'en', 'Competitive rates'),
('login', 'login-beneficio1', 'es', 'Tasas competitivas'),
('login', 'login-beneficio2', 'en', '\r\nGuaranteed security'),
('login', 'login-beneficio2', 'es', 'Seguridad garanrtizada'),
('login', 'login-beneficio3', 'en', 'Personalized attention'),
('login', 'login-beneficio3', 'es', 'Atención personalizada'),
('login', 'login-btn', 'en', 'Log in'),
('login', 'login-btn', 'es', 'Ingresar'),
('login', 'login-texto-side', 'en', 'Access all the benefits of being part of our financial community'),
('login', 'login-texto-side', 'es', 'Accede a todos los beneficios de ser parte de nuestra comunidad financiera'),
('login', 'login-titulo', 'en', 'Log in to your account'),
('login', 'login-titulo', 'es', 'Ingrese a su cuenta'),
('login', 'login-titulo-side', 'en', 'Welcome to Senda Firme'),
('login', 'login-titulo-side', 'es', 'Bienvenido a Senda Firme'),
('login', 'no-cuenta-link', 'en', 'Sign in here'),
('login', 'no-cuenta-link', 'es', 'Crea tu cuenta aquí'),
('login', 'no-cuenta-text', 'en', 'Do not have an account yet?'),
('login', 'no-cuenta-text', 'es', '¿Aun no tienes una cuenta?'),
('registro', 'cuenta-link', 'en', 'Log in here'),
('registro', 'cuenta-link', 'es', 'Inicia sesión aquí'),
('registro', 'cuenta-text', 'en', 'Already have an account?\r\n\r\n'),
('registro', 'cuenta-text', 'es', '¿Ya tienes una cuenta?'),
('registro', 'registro-btn', 'en', 'Sign In'),
('registro', 'registro-btn', 'es', 'Registrarse'),
('registro', 'registro-form', 'en', 'Name;Last Name;Email Address;Phone number;National ID;Password;Confirm Password;I accept the <a href=\"#\">Terms of Service</a> and <a href=\"#\">Privacy Policy</a>'),
('registro', 'registro-form', 'es', 'Nombre;Apellido;Correo electrónico;Teléfono Móvil;Cédula de Identidad;Contraseña;Confirmar Contraseña;Acepto los <a href=\"#\">Términos de servicio</a> y <a href=\"#\">Política de\n                            privacidad'),
('registro', 'registro-titulo', 'en', 'Create your account'),
('registro', 'registro-titulo', 'es', 'Crea tu cuenta'),
('usuario','sidebar-slogan','es','Construyendo oportunidades juntos'),
('usuario','sidebar-slogan','en','Building opportunities together'),
('usuario','sidebar-menu-inicio','es','Inicio'),
('usuario','sidebar-menu-inicio','en','Home'),
('usuario','sidebar-menu-horas','es','Horas Trabajadas'),
('usuario','sidebar-menu-horas','en','Worked hours'),
('usuario','sidebar-menu-unidad','es','Unidad Habitacional'),
('usuario','sidebar-menu-unidad','en','Housing unit'),
('usuario','sidebar-menu-pagos','es','Pagos'),
('usuario','sidebar-menu-pagos','en','Payments'),
('usuario','sidebar-menu-configuracion','es','Configuración'),
('usuario','sidebar-menu-configuracion','en','Settings'),
('usuario','perfil-rol','es','Usuario'),
('usuario','perfil-rol','en','User'),
('usuario','btn-cerrar-sesion','es','Cerrar sesión'),
('usuario','btn-cerrar-sesion','en','Log out'),
('usuario','btn-cambiar-sesion','es','Cambiar a Admin'),
('usuario','btn-cambiar-sesion','en','Switch to Admin'),
('usuario','dashboard-header-titulo','es','Bienvenido,'),
('usuario','dashboard-header-titulo','en','Welcome,'),
('usuario','dashboard-header-subtitulo','es','Aquí puedes gestionar todas tus actividades en la cooperativa'),
('usuario','dashboard-header-subtitulo','en','Here you can manage all your activities in the cooperative'),
('usuario','card-pagos-titulo','es','Pagos Atrasados'),
('usuario','card-pagos-titulo','en','Overdue payments'),
('usuario','card-pagos-subtexto','es','Total: $0'),
('usuario','card-pagos-subtexto','en','Total: $0'),
('usuario','card-horas-titulo','es','Horas Trabajadas'),
('usuario','card-horas-titulo','en','Worked hours'),
('usuario','card-horas-subtexto','es','Esta Semana'),
('usuario','card-horas-subtexto','en','This week'),
('usuario','card-reuniones-titulo','es','Reuniones'),
('usuario','card-reuniones-titulo','en','Meetings'),
('usuario','card-reuniones-subtexto','es','Próximas'),
('usuario','card-reuniones-subtexto','en','Upcoming'),
('usuario','card-asistencias-titulo','es','Asistencias'),
('usuario','card-asistencias-titulo','en','Attendance'),
('usuario','card-asistencias-subtexto','es','De las reuniones'),
('usuario','card-asistencias-subtexto','en','Of the meetings'),
('usuario','seccion-reuniones-completadas-titulo','es','Reuniones Completadas'),
('usuario','seccion-reuniones-completadas-titulo','en','Completed meetings'),
('usuario','seccion-proximas-reuniones-titulo','es','Proximas Reuniones'),
('usuario','seccion-proximas-reuniones-titulo','en','Upcoming meetings'),
('usuario','modal-titulo','es','Detalles de la Reunión'),
('usuario','modal-titulo','en','Meeting details'),
('usuario','modal-estado-label','es','Estado'),
('usuario','modal-estado-label','en','Status'),
('usuario','modal-fecha-label','es','Fecha y Hora'),
('usuario','modal-fecha-label','en','Date and time'),
('usuario','modal-ubicacion-label','es','Ubicación'),
('usuario','modal-ubicacion-label','en','Location'),
('usuario','modal-descripcion-label','es','Descripción'),
('usuario','modal-descripcion-label','en','Description'),
('usuario','modal-boton-cerrar','es','Cerrar'),
('usuario','modal-boton-cerrar','en','Close')
('unidad-usuario','sidebar-slogan','es','Construyendo oportunidades juntos'),
('unidad-usuario','sidebar-slogan','en','Building opportunities together'),
('unidad-usuario','menu-inicio','es','Inicio'),
('unidad-usuario','menu-inicio','en','Home'),
('unidad-usuario','menu-horas-trabajadas','es','Horas Trabajadas'),
('unidad-usuario','menu-horas-trabajadas','en','Worked Hours'),
('unidad-usuario','menu-unidad-habitacional','es','Unidad Habitacional'),
('unidad-usuario','menu-unidad-habitacional','en','Housing Unit'),
('unidad-usuario','menu-pagos','es','Pagos'),
('unidad-usuario','menu-pagos','en','Payments'),
('unidad-usuario','menu-configuracion','es','Configuración'),
('unidad-usuario','menu-configuracion','en','Settings'),
('unidad-usuario','sidebar-rol-usuario','es','Usuario'),
('unidad-usuario','sidebar-rol-usuario','en','User'),
('unidad-usuario','boton-cerrar-sesion','es','Cerrar sesión'),
('unidad-usuario','boton-cerrar-sesion','en','Log out'),
('unidad-usuario','boton-cambiar-admin','es','Cambiar a Admin'),
('unidad-usuario','boton-cambiar-admin','en','Switch to Admin'),
('unidad-usuario','unidad-titulo','es','Unidad Habitacional'),
('unidad-usuario','unidad-titulo','en','Housing Unit'),
('unidad-usuario','unidad-subtitulo','es','Gestiona los datos de tu vivienda y los integrantes de tu familia'),
('unidad-usuario','unidad-subtitulo','en','Manage your home data and your family members'),
('unidad-usuario','unidad-info-titulo','es','Información de la Unidad'),
('unidad-usuario','unidad-info-titulo','en','Unit Information'),
('unidad-usuario','unidad-numero-label','es','Número de Unidad:'),
('unidad-usuario','unidad-numero-label','en','Unit Number:'),
('unidad-usuario','unidad-pasillo-label','es','Pasillo:'),
('unidad-usuario','unidad-pasillo-label','en','Hallway:'),
('unidad-usuario','unidad-estado-label','es','Estado:'),
('unidad-usuario','unidad-estado-label','en','Status:'),
('unidad-usuario','unidad-habitaciones-label','es','Habitaciones:'),
('unidad-usuario','unidad-habitaciones-label','en','Rooms:'),
('unidad-usuario','integrantes-titulo','es','Integrantes Familiares'),
('unidad-usuario','integrantes-titulo','en','Family Members'),
('unidad-usuario','integrantes-boton-agregar','es','Agregar Integrante'),
('unidad-usuario','integrantes-boton-agregar','en','Add Member'),
('unidad-usuario','integrantes-tabla-nombre','es','Nombre'),
('unidad-usuario','integrantes-tabla-nombre','en','First Name'),
('unidad-usuario','integrantes-tabla-apellido','es','Apellido'),
('unidad-usuario','integrantes-tabla-apellido','en','Last Name'),
('unidad-usuario','integrantes-tabla-ci','es','CI'),
('unidad-usuario','integrantes-tabla-ci','en','ID'),
('unidad-usuario','integrantes-tabla-mail','es','Mail'),
('unidad-usuario','integrantes-tabla-mail','en','Email'),
('unidad-usuario','integrantes-tabla-fecha-nacimiento','es','Fecha de Nacimiento'),
('unidad-usuario','integrantes-tabla-fecha-nacimiento','en','Date of Birth'),
('unidad-usuario','integrantes-tabla-genero','es','Genero'),
('unidad-usuario','integrantes-tabla-genero','en','Gender'),
('unidad-usuario','integrantes-tabla-acciones','es','Acciones'),
('unidad-usuario','integrantes-tabla-acciones','en','Actions'),
('unidad-usuario','integrantes-vacio-titulo','es','No hay integrantes familiares registrados'),
('unidad-usuario','integrantes-vacio-titulo','en','There are no registered family members'),
('unidad-usuario','integrantes-vacio-texto','es','Agrega los integrantes de tu familia para gestionarlos desde aquí'),
('unidad-usuario','integrantes-vacio-texto','en','Add your family members to manage them here'),
('unidad-usuario','modal-integrante-titulo-agregar','es','Agregar Integrante Familiar'),
('unidad-usuario','modal-integrante-titulo-agregar','en','Add Family Member'),
('unidad-usuario','modal-integrante-mensaje-exito','es','Integrante guardado correctamente.'),
('unidad-usuario','modal-integrante-mensaje-exito','en','Member saved successfully.'),
('unidad-usuario','modal-integrante-mensaje-error','es','Error al guardar el integrante.'),
('unidad-usuario','modal-integrante-mensaje-error','en','Error while saving the member.'),
('unidad-usuario','modal-integrante-label-nombre','es','Nombre:'),
('unidad-usuario','modal-integrante-label-nombre','en','First Name:'),
('unidad-usuario','modal-integrante-label-apellido','es','Apellido:'),
('unidad-usuario','modal-integrante-label-apellido','en','Last Name:'),
('unidad-usuario','modal-integrante-label-ci','es','Cedula:'),
('unidad-usuario','modal-integrante-label-ci','en','ID Number:'),
('unidad-usuario','modal-integrante-label-email','es','Email:'),
('unidad-usuario','modal-integrante-label-email','en','Email:'),
('unidad-usuario','modal-integrante-label-fecha-nacimiento','es','Fecha de Nacimiento:'),
('unidad-usuario','modal-integrante-label-fecha-nacimiento','en','Date of Birth:'),
('unidad-usuario','modal-integrante-select-placeholder','es','Seleccioná…'),
('unidad-usuario','modal-integrante-select-placeholder','en','Select…'),
('unidad-usuario','modal-integrante-select-masculino','es','Masculino'),
('unidad-usuario','modal-integrante-select-masculino','en','Male'),
('unidad-usuario','modal-integrante-select-femenino','es','Femenino'),
('unidad-usuario','modal-integrante-select-femenino','en','Female'),
('unidad-usuario','modal-boton-cancelar','es','Cancelar'),
('unidad-usuario','modal-boton-cancelar','en','Cancel'),
('unidad-usuario','modal-boton-guardar','es','Guardar'),
('unidad-usuario','modal-boton-guardar','en','Save'),
('unidad-usuario','modal-confirmacion-titulo','es','Confirmar Eliminación'),
('unidad-usuario','modal-confirmacion-titulo','en','Confirm Deletion'),
('unidad-usuario','modal-confirmacion-texto','es','¿Estás seguro de que deseas eliminar este integrante familiar?'),
('unidad-usuario','modal-confirmacion-texto','en','Are you sure you want to delete this family member?'),
('unidad-usuario','modal-boton-eliminar','es','Eliminar'),
('unidad-usuario','modal-boton-eliminar','en','Delete'),
('horas','horas-header-titulo','es','Horas Trabajadas'),
('horas','horas-header-titulo','en','Worked hours'),
('horas','horas-header-subtitulo','es','Registra y consulta tus horas de trabajo semanales en la cooperativa'),
('horas','horas-header-subtitulo','en','Record and view your weekly working hours in the cooperative'),
('horas','contador-titulo','es','Resumen de Horas'),
('horas','contador-titulo','en','Hours summary'),
('horas','contador-label-trabajadas','es','Horas trabajadas esta semana'),
('horas','contador-label-trabajadas','en','Hours worked this week'),
('horas','contador-label-objetivo','es','Meta semanal'),
('horas','contador-label-objetivo','en','Weekly goal'),
('horas','contador-label-restantes','es','Horas restantes'),
('horas','contador-label-restantes','en','Remaining hours'),
('horas','contador-texto-progreso','es','Completado'),
('horas','contador-texto-progreso','en','Completed'),
('horas','pestana-horas-texto','es','Registrar Horas'),
('horas','pestana-horas-texto','en','Register hours'),
('horas','pestana-faltas-texto','es','Registrar Faltas'),
('horas','pestana-faltas-texto','en','Register absences'),
('horas','horas-form-titulo','es','Registrar horas trabajadas'),
('horas','horas-form-titulo','en','Register worked hours'),
('horas','horas-form-msg-exito','es','Horas registradas correctamente.'),
('horas','horas-form-msg-exito','en','Hours successfully recorded.'),
('horas','horas-form-msg-error','es','Error al registrar las horas.'),
('horas','horas-form-msg-error','en','Error while recording hours.'),
('horas','horas-form-label-horas','es','Horas trabajadas:'),
('horas','horas-form-label-horas','en','Worked hours:'),
('horas','horas-form-texto-ayuda-1','es','Ingresa la cantidad de horas que trabajaste'),
('horas','horas-form-texto-ayuda-1','en','Enter the number of hours you worked'),
('horas','horas-form-texto-ayuda-2','es','Recorda que siempre redondeamos para abajo'),
('horas','horas-form-texto-ayuda-2','en','Remember that we always round down'),
('horas','horas-form-btn-texto','es','Registrar horas'),
('horas','horas-form-btn-texto','en','Record hours'),
('horas','sidebar-slogan','es','Construyendo oportunidades juntos'),
('horas','sidebar-slogan','en','Building opportunities together'),
('horas','sidebar-menu-inicio','es','Inicio'),
('horas','sidebar-menu-inicio','en','Home'),
('horas','sidebar-menu-horas','es','Horas Trabajadas'),
('horas','sidebar-menu-horas','en','Worked hours'),
('horas','sidebar-menu-unidad','es','Unidad Habitacional'),
('horas','sidebar-menu-unidad','en','Housing unit'),
('horas','sidebar-menu-pagos','es','Pagos'),
('horas','sidebar-menu-pagos','en','Payments'),
('horas','sidebar-menu-configuracion','es','Configuración'),
('horas','sidebar-menu-configuracion','en','Settings'),
('horas','perfil-rol','es','Usuario'),
('horas','perfil-rol','en','User'),
('horas','btn-cerrar-sesion','es','Cerrar sesión'),
('horas','btn-cerrar-sesion','en','Log out'),
('horas','btn-cambiar-sesion','es','Cambiar a Admin'),
('horas','btn-cambiar-sesion','en','Switch to Admin'),
('horas','faltas-form-titulo','es','Registrar Faltas'),
('horas','faltas-form-titulo','en','Register absences'),
('horas','faltas-form-texto-opciones','es','Opciones de compensación:'),
('horas','faltas-form-texto-opciones','en','Compensation options:'),
('horas','faltas-form-item-exoneracion','es','Exoneración: Se descuentan las horas faltadas de tu objetivo semanal'),
('horas','faltas-form-item-exoneracion','en','Exemption: The missed hours are deducted from your weekly goal'),
('horas','faltas-form-item-pago','es','Compensación monetaria: Pagas una tarifa establecida por la cooperativa por las horas que no trabajaste'),
('horas','faltas-form-item-pago','en','Monetary compensation: You pay a fee set by the cooperative for the hours you did not work'),
('horas','faltas-form-msg-exito','es','Falta registrada correctamente.'),
('horas','faltas-form-msg-exito','en','Absence successfully recorded.'),
('horas','faltas-form-msg-error','es','Error al registrar la falta.'),
('horas','faltas-form-msg-error','en','Error while recording the absence.'),
('horas','faltas-form-label-horas','es','Horas faltadas:'),
('horas','faltas-form-label-horas','en','Missed hours:'),
('horas','faltas-form-label-tipo','es','Tipo de compensación:'),
('horas','faltas-form-label-tipo','en','Compensation type:'),
('horas','faltas-form-option-placeholder','es','Selecciona una opción'),
('horas','faltas-form-option-placeholder','en','Select an option'),
('horas','faltas-form-option-exoneracion','es','Exoneración de horas'),
('horas','faltas-form-option-exoneracion','en','Hours exemption'),
('horas','faltas-form-option-pago','es','Compensación monetaria'),
('horas','faltas-form-option-pago','en','Monetary compensation'),
('horas','faltas-form-label-motivo','es','Motivo de la falta:'),
('horas','faltas-form-label-motivo','en','Reason for the absence:'),
('horas','faltas-form-btn-texto','es','Registrar falta'),
('horas','faltas-form-btn-texto','en','Record absence'),
('horas','historial-titulo','es','Historial de horas trabajadas'),
('horas','historial-titulo','en','Worked hours history'),
('horas','historial-filtro-semana-label','es','Semana:'),
('horas','historial-filtro-semana-label','en','Week:'),
('horas','historial-filtro-semana-option-todas','es','Todas'),
('horas','historial-filtro-semana-option-todas','en','All'),
('horas','historial-filtro-dia-label','es','Dia:'),
('horas','historial-filtro-dia-label','en','Day:'),
('horas','historial-filtro-dia-option-todos','es','Todos'),
('horas','historial-filtro-dia-option-todos','en','All'),
('horas','historial-filtro-dia-option-1','es','Lunes'),
('horas','historial-filtro-dia-option-1','en','Monday'),
('horas','historial-filtro-dia-option-2','es','Martes'),
('horas','historial-filtro-dia-option-2','en','Tuesday'),
('horas','historial-filtro-dia-option-3','es','Miercoles'),
('horas','historial-filtro-dia-option-3','en','Wednesday'),
('horas','historial-filtro-dia-option-4','es','Jueves'),
('horas','historial-filtro-dia-option-4','en','Thursday'),
('horas','historial-filtro-dia-option-5','es','Viernes'),
('horas','historial-filtro-dia-option-5','en','Friday'),
('horas','historial-filtro-dia-option-6','es','Sabado'),
('horas','historial-filtro-dia-option-6','en','Saturday'),
('horas','historial-filtro-dia-option-7','es','Domingo'),
('horas','historial-filtro-dia-option-7','en','Sunday'),
('horas','tabla-horas-th-fecha','es','Fecha'),
('horas','tabla-horas-th-fecha','en','Date'),
('horas','tabla-horas-th-dia','es','Día'),
('horas','tabla-horas-th-dia','en','Day'),
('horas','tabla-horas-th-horas','es','Horas'),
('horas','tabla-horas-th-horas','en','Hours'),
('horas','tabla-horas-th-editar','es','Editar'),
('horas','tabla-horas-th-editar','en','Edit'),
('horas','tabla-horas-th-borrar','es','Borrar'),
('horas','tabla-horas-th-borrar','en','Delete'),
('horas','modal-editar-titulo','es','Editar horas trabajadas'),
('horas','modal-editar-titulo','en','Edit worked hours'),
('horas','modal-editar-msg-exito','es','Horas actualizadas correctamente.'),
('horas','modal-editar-msg-exito','en','Hours successfully updated.'),
('horas','modal-editar-msg-error','es','Error al actualizar las horas.'),
('horas','modal-editar-msg-error','en','Error while updating hours.'),
('horas','modal-editar-label-fecha','es','Fecha:'),
('horas','modal-editar-label-fecha','en','Date:'),
('horas','modal-editar-label-horas','es','Horas trabajadas:'),
('horas','modal-editar-label-horas','en','Worked hours:'),
('horas','modal-editar-boton-cancelar','es','Cancelar'),
('horas','modal-editar-boton-cancelar','en','Cancel'),
('horas','modal-editar-boton-guardar','es','Guardar cambios'),
('horas','modal-editar-boton-guardar','en','Save changes'),
('pagos-usuario','sidebar-slogan','es','Construyendo oportunidades juntos'),
('pagos-usuario','sidebar-slogan','en','Building opportunities together'),
('pagos-usuario','menu-inicio','es','Inicio'),
('pagos-usuario','menu-inicio','en','Home'),
('pagos-usuario','menu-horas-trabajadas','es','Horas Trabajadas'),
('pagos-usuario','menu-horas-trabajadas','en','Worked Hours'),
('pagos-usuario','menu-unidad-habitacional','es','Unidad Habitacional'),
('pagos-usuario','menu-unidad-habitacional','en','Housing Unit'),
('pagos-usuario','menu-pagos','es','Pagos'),
('pagos-usuario','menu-pagos','en','Payments'),
('pagos-usuario','menu-configuracion','es','Configuración'),
('pagos-usuario','menu-configuracion','en','Settings'),
('pagos-usuario','sidebar-rol-usuario','es','Usuario'),
('pagos-usuario','sidebar-rol-usuario','en','User'),
('pagos-usuario','boton-cerrar-sesion','es','Cerrar sesión'),
('pagos-usuario','boton-cerrar-sesion','en','Log out'),
('pagos-usuario','boton-cambiar-admin','es','Cambiar a Admin'),
('pagos-usuario','boton-cambiar-admin','en','Switch to Admin'),
('pagos-usuario','pagos-titulo','es','Pagos Pendientes'),
('pagos-usuario','pagos-titulo','en','Pending Payments'),
('pagos-usuario','pagos-subtitulo','es','Consulta y gestiona tus pagos pendientes con la cooperativa'),
('pagos-usuario','pagos-subtitulo','en','Check and manage your pending payments with the cooperative'),
('pagos-usuario','card-pagos-pendientes-titulo','es','Pagos Pendientes'),
('pagos-usuario','card-pagos-pendientes-titulo','en','Pending Payments'),
('pagos-usuario','card-pagos-pendientes-subtexto','es','Cantidad total'),
('pagos-usuario','card-pagos-pendientes-subtexto','en','Total amount'),
('pagos-usuario','card-monto-total-titulo','es','Monto Total'),
('pagos-usuario','card-monto-total-titulo','en','Total Amount'),
('pagos-usuario','card-monto-total-subtexto','es','Por pagar'),
('pagos-usuario','card-monto-total-subtexto','en','To be paid'),
('pagos-usuario','card-ultimo-pago-titulo','es','Ultimo Pago'),
('pagos-usuario','card-ultimo-pago-titulo','en','Last Payment'),
('pagos-usuario','card-ultimo-pago-subtexto','es','Monto del ultimo pago a realizar'),
('pagos-usuario','card-ultimo-pago-subtexto','en','Amount of the last payment'),
('pagos-usuario','pagos-mensaje-exito','es','Pago general registrado correctamente, a la espera de la aprobacion de un administrador'),
('pagos-usuario','pagos-mensaje-exito','en','General payment registered successfully, pending approval from an administrator'),
('pagos-usuario','seccion-detalle-pagos-titulo','es','Detalle de Pagos Atrasados'),
('pagos-usuario','seccion-detalle-pagos-titulo','en','Detail of Overdue Payments'),
('pagos-usuario','filtros-estado-label','es','Estado:'),
('pagos-usuario','filtros-estado-label','en','Status:'),
('pagos-usuario','filtros-estado-opcion-todos','es','Todos'),
('pagos-usuario','filtros-estado-opcion-todos','en','All'),
('pagos-usuario','filtros-estado-opcion-pendiente','es','Pendiente'),
('pagos-usuario','filtros-estado-opcion-pendiente','en','Pending'),
('pagos-usuario','filtros-estado-opcion-en-espera','es','En Espera'),
('pagos-usuario','filtros-estado-opcion-en-espera','en','On hold'),
('pagos-usuario','filtros-tipo-label','es','Tipo de Pago'),
('pagos-usuario','filtros-tipo-label','en','Type of Payment'),
('pagos-usuario','filtros-tipo-opcion-todos','es','Todos'),
('pagos-usuario','filtros-tipo-opcion-todos','en','All'),
('pagos-usuario','filtros-tipo-opcion-mensual','es','Mensual'),
('pagos-usuario','filtros-tipo-opcion-mensual','en','Monthly'),
('pagos-usuario','filtros-tipo-opcion-otros','es','Otros'),
('pagos-usuario','filtros-tipo-opcion-otros','en','Others'),
('pagos-usuario','filtros-boton-aplicar','es','Aplicar Filtros'),
('pagos-usuario','filtros-boton-aplicar','en','Apply Filters'),
('pagos-usuario','filtros-boton-realizar-pago','es','Realizar Pago'),
('pagos-usuario','filtros-boton-realizar-pago','en','Make Payment'),
('pagos-usuario','tabla-pagos-columna-concepto','es','Concepto'),
('pagos-usuario','tabla-pagos-columna-concepto','en','Concept'),
('pagos-usuario','tabla-pagos-columna-monto','es','Monto'),
('pagos-usuario','tabla-pagos-columna-monto','en','Amount'),
('pagos-usuario','tabla-pagos-columna-fecha','es','Fecha del Pago'),
('pagos-usuario','tabla-pagos-columna-fecha','en','Payment Date'),
('pagos-usuario','tabla-pagos-columna-estado','es','Estado'),
('pagos-usuario','tabla-pagos-columna-estado','en','Status'),
('pagos-usuario','tabla-pagos-columna-acciones','es','Acciones'),
('pagos-usuario','tabla-pagos-columna-acciones','en','Actions'),
('pagos-usuario','modal-pago-titulo','es','Realizar Pago'),
('pagos-usuario','modal-pago-titulo','en','Make Payment'),
('pagos-usuario','modal-pago-label-seleccionar','es','Seleccionar pago a realizar:'),
('pagos-usuario','modal-pago-label-seleccionar','en','Select a payment to make:'),
('pagos-usuario','modal-pago-opcion-placeholder','es','Seleccione un pago'),
('pagos-usuario','modal-pago-opcion-placeholder','en','Select a payment'),
('pagos-usuario','modal-pago-detalles-titulo','es','Detalles del pago seleccionado'),
('pagos-usuario','modal-pago-detalles-titulo','en','Selected payment details'),
('pagos-usuario','modal-pago-label-concepto','es','Concepto:'),
('pagos-usuario','modal-pago-label-concepto','en','Concept:'),
('pagos-usuario','modal-pago-label-monto','es','Monto:'),
('pagos-usuario','modal-pago-label-monto','en','Amount:'),
('pagos-usuario','modal-pago-label-vencimiento','es','Fecha de vencimiento:'),
('pagos-usuario','modal-pago-label-vencimiento','en','Due date:'),
('pagos-usuario','modal-pago-label-comprobante','es','Comprobante de pago:'),
('pagos-usuario','modal-pago-label-comprobante','en','Proof of payment:'),
('pagos-usuario','modal-pago-boton-archivo','es','Seleccionar archivo'),
('pagos-usuario','modal-pago-boton-archivo','en','Select file'),
('pagos-usuario','modal-pago-archivo-placeholder','es','Ningún archivo seleccionado'),
('pagos-usuario','modal-pago-archivo-placeholder','en','No file selected'),
('pagos-usuario','modal-pago-texto-ayuda','es','Formatos aceptados: PDF, JPG, PNG (Tamaño máximo: 5MB)'),
('pagos-usuario','modal-pago-texto-ayuda','en','Accepted formats: PDF, JPG, PNG (Maximum size: 5MB)'),
('pagos-usuario','modal-boton-cancelar','es','Cancelar'),
('pagos-usuario','modal-boton-cancelar','en','Cancel'),
('pagos-usuario','modal-boton-confirmar','es','Confirmar Pago'),
('pagos-usuario','modal-boton-confirmar','en','Confirm Payment'),
('configuracion-usuario','sidebar-slogan','es','Construyendo oportunidades juntos'),
('configuracion-usuario','sidebar-slogan','en','Building opportunities together'),
('configuracion-usuario','menu-inicio','es','Inicio'),
('configuracion-usuario','menu-inicio','en','Home'),
('configuracion-usuario','menu-horas-trabajadas','es','Horas Trabajadas'),
('configuracion-usuario','menu-horas-trabajadas','en','Worked Hours'),
('configuracion-usuario','menu-unidad-habitacional','es','Unidad Habitacional'),
('configuracion-usuario','menu-unidad-habitacional','en','Housing Unit'),
('configuracion-usuario','menu-pagos','es','Pagos'),
('configuracion-usuario','menu-pagos','en','Payments'),
('configuracion-usuario','menu-configuracion','es','Configuración'),
('configuracion-usuario','menu-configuracion','en','Settings'),
('configuracion-usuario','sidebar-rol-usuario','es','Usuario'),
('configuracion-usuario','sidebar-rol-usuario','en','User'),
('configuracion-usuario','boton-cerrar-sesion','es','Cerrar sesión'),
('configuracion-usuario','boton-cerrar-sesion','en','Log out'),
('configuracion-usuario','boton-cambiar-admin','es','Cambiar a Admin'),
('configuracion-usuario','boton-cambiar-admin','en','Switch to Admin'),
('configuracion-usuario','perfil-titulo','es','Mi Perfil'),
('configuracion-usuario','perfil-titulo','en','My Profile'),
('configuracion-usuario','perfil-subtitulo','es','Gestiona tu información personal y preferencias'),
('configuracion-usuario','perfil-subtitulo','en','Manage your personal information and preferences'),
('configuracion-usuario','boton-cambiar-foto','es','Cambiar foto'),
('configuracion-usuario','boton-cambiar-foto','en','Change photo'),
('configuracion-usuario','boton-cambiar-datos-personales','es','Cambiar datos personales'),
('configuracion-usuario','boton-cambiar-datos-personales','en','Edit personal data'),
('configuracion-usuario','info-personal-titulo','es','Información personal'),
('configuracion-usuario','info-personal-titulo','en','Personal information'),
('configuracion-usuario','perfil-label-nombre','es','Nombre'),
('configuracion-usuario','perfil-label-nombre','en','First Name'),
('configuracion-usuario','perfil-label-apellido','es','Apellido'),
('configuracion-usuario','perfil-label-apellido','en','Last Name'),
('configuracion-usuario','perfil-label-email','es','Correo electrónico'),
('configuracion-usuario','perfil-label-email','en','Email'),
('configuracion-usuario','perfil-label-telefono','es','Teléfono'),
('configuracion-usuario','perfil-label-telefono','en','Phone'),
('configuracion-usuario','perfil-label-fecha-nacimiento','es','Fecha de Nacimiento'),
('configuracion-usuario','perfil-label-fecha-nacimiento','en','Date of Birth'),
('configuracion-usuario','perfil-label-direccion','es','Dirección'),
('configuracion-usuario','perfil-label-direccion','en','Address'),
('configuracion-usuario','perfil-label-fecha-ingreso','es','Fecha de Ingreso a la cooperativa'),
('configuracion-usuario','perfil-label-fecha-ingreso','en','Date of joining the cooperative'),
('configuracion-usuario','perfil-boton-guardar-cambios','es','Guardar cambios'),
('configuracion-usuario','perfil-boton-guardar-cambios','en','Save changes'),
('configuracion-usuario','perfil-boton-cancelar','es','Cancelar'),
('configuracion-usuario','perfil-boton-cancelar','en','Cancel'),
('configuracion-usuario','perfil-label-nombre-completo','es','Nombre completo'),
('configuracion-usuario','perfil-label-nombre-completo','en','Full name'),
('configuracion-usuario','estadisticas-titulo','es','Mis estadísticas'),
('configuracion-usuario','estadisticas-titulo','en','My statistics'),
('configuracion-usuario','estadistica-total-horas-titulo','es','Total Horas Trabajadas'),
('configuracion-usuario','estadistica-total-horas-titulo','en','Total hours worked'),
('configuracion-usuario','estadistica-monto-aportado-titulo','es','Monto Aportado'),
('configuracion-usuario','estadistica-monto-aportado-titulo','en','Amount contributed'),
('configuracion-usuario','estadistica-antiguedad-titulo','es','Antigüedad'),
('configuracion-usuario','estadistica-antiguedad-titulo','en','Seniority'),






;